
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: veto_dev
  username: veto
  password: veto

test:
  <<: *default
  database: veto_test
  username: veto
  password: veto

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
